### ISSUE TITLE
cannot build on Node 12.14.1

### ISSUE THREAD

**Issue by snoblenet** [remko/node-itunes-db#2]
Is it possible to bump this package so it builds on Node 12.14.1 please?

Error is:

```
12:53PM ~/code/plex-itunes-import npm install

> itunes-db@0.4.0 install /Users/steven/code/plex-itunes-import/node_modules/itunes-db
> node-gyp rebuild

  CXX(target) Release/obj.target/itunes_db/itunes-db.o
../itunes-db.cpp:54:60: error: no matching member function for call to 'ToString'
                                                        std::string id(*v8::String::Utf8Value(persistentID->ToString()));
                                                                                              ~~~~~~~~~~~~~~^~~~~~~~
/Users/steven/Library/Caches/node-gyp/12.14.1/include/node/v8.h:2572:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/steven/Library/Caches/node-gyp/12.14.1/include/node/v8.h:2588:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
../itunes-db.cpp:198:49: error: no matching member function for call to 'ToString'
        std::string db(*v8::String::Utf8Value(info[0]->ToString()));
                                              ~~~~~~~~~^~~~~~~~
/Users/steven/Library/Caches/node-gyp/12.14.1/include/node/v8.h:2572:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
                                           ^
/Users/steven/Library/Caches/node-gyp/12.14.1/include/node/v8.h:2588:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<String> ToString(Isolate* isolate) const);
                              ^
2 errors generated.
make: *** [Release/obj.target/itunes_db/itunes-db.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node@12/12.14.1_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/steven/code/plex-itunes-import/node_modules/itunes-db
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
```

**Comment by snoblenet** [comment]
started building my own personal use alternative

**Comment by remko** [comment]
Patches always welcome!

**Comment by dersimn** [comment]
> started building my own personal use alternative

Can you provide the Repository URL?

**Comment by snoblenet** [comment]
sorry i never completed that project as i stopped using Plex so i no longer needed to try to sync it properly with iTunes

it's simpler to go iTunes all the way until i consider moving to another platform entirely
